MARKDOWN=markdown

CONF=config.mk header.html main.css

HTML=index.html \
	about.html \
	changelog.html \
	content_warning.html \
	contributions.html \
	now.html \
	todo.html \
	uses_this.html \
	reports.html \
	notes.html \
	notes_on_ethics.html \
	notes_on_politics_especially_economics.html \
	notes_on_predictions.html \
	administrativa_for_facts.html \
	administrativa_for_textbooks.html \
	aima_solutions.html \
	apisct_solutions.html \
	nst_solutions.html \
	pil_solutions.html \
	pg_solutions.html \
	praml_solutions.html \
	rs_solutions.html \
	tjpb_exercises.html \
	99_klong_problems.html \
	99_problems_collection.html \
	99_problems_klong_solution.html \
	against_applause.html \
	bcis_and_alignment.html \
	buch_stab.html \
	circle_combinations.html \
	consciousness_diagram.html \
	considerations_on_cryonics.html \
	cryonics_outside_us.html \
	daygame_cost_benefit.html \
	declaration.html \
	epigrams.html \
	equally_many_heads_and_tails.html \
	estimated_life_expectancy.html \
	exercise_log.html \
	flags.html \
	generalizing_diamond_square.html \
	language.html \
	leave_the_internet.html \
	life_advice.html \
	life_improvements_2030.html \
	masturbation_and_attractiveness.html \
	mathematics_notation_convention.html \
	metamodernistisches_manifest.html \
	microfiction.html \
	pipe_rings.html \
	platte.html \
	range_and_forecasting_accuracy.html \
	rationalist_gods.html \
	senryu.html \
	sites.html \
	tao_te_king.html \
	text_reviews.html \
	textbook_discord_servers.html \
	toy_ai_takeoff_model.html \
	two_people_on_a_planet.html \
	utilitarian_compliments.html \
	bp_chrono.html \
	ob_chrono.html \
	so_chrono.html \
	trm_chrono.html \
	awitt.html \
	movies_list.html \
	podcasts_list.html \
	series_list.html \
	texts_list.html
