#!/usr/bin/env node

const mjpage = require('mathjax-node-page').mjpage;
const fs = require('fs');

if (process.argv.length !== 3) {
    console.error('Usage: prerender-mathjax <html-file>');
    process.exit(1);
}

const filename = process.argv[2];

try {
    let html = fs.readFileSync(filename, 'utf8');
    const protectedBlocks = [];

    html = html.replace(/<code[^>]*>\$([^<>$]+?)\$<\/code>|<div[^>]*>(\s*)\$\$([^<>$]+?)\$\$(\s*)<\/div>/g,
        function(match, inlineContent, preDiv, displayContent, postDiv) {
            const placeholder = `__PROTECTED_${protectedBlocks.length}__`;
            if (inlineContent !== undefined) {
                protectedBlocks.push(`$${inlineContent}$`);
            } else {
                protectedBlocks.push(`<div>${preDiv}$$${displayContent}$$${postDiv}</div>`);
            }
            return placeholder;
        }
    );

    html = html.replace(/<code[^>]*>([^]*?)<\/code>|<pre[^>]*>([^]*?)<\/pre>/g,
        function(match) {
            const placeholder = `__PROTECTED_${protectedBlocks.length}__`;
            protectedBlocks.push(match);
            return placeholder;
        }
    );

    html = html.replace(/(?<!\\)\$/g, '\\$');
    html = html.replace(/__PROTECTED_(\d+)__/g, (match, index) => protectedBlocks[parseInt(index)]);

    mjpage(html, {
        format: ["TeX"],
        singleDollars: true,
        removeJax: true
    }, {
        svg: true,
        useGlobalCache: true,
        linebreaks: true,
        MathJax: {
            tex2jax: {
                skipTags: []
            }
        }
    }, function(output) {
        try {
            fs.writeFileSync(filename, output);
        } catch (err) {
            console.error(`Error writing file ${filename}:`, err.message);
            process.exit(1);
        }
    });
} catch (err) {
    console.error(`Error reading file ${filename}:`, err.message);
    process.exit(1);
}