all:
	make -C 99_klong/
	make -C considerations_on_cryonics/
	make -C daygame_cost_benefit/
	make -C estimated_life_expectancy/
	make -C short_and_mid_range_forecasting_accuracy/
	make -C masturbation_and_attractiveness/
	make -C naive_set_theory/
	make -C bp_chrono/
	make -C ob_chrono/
	make -C so_chrono/
	make -C trm_chrono/

puttit:
	make -C 99_klong/ puttit
	make -C considerations_on_cryonics/ puttit
	make -C daygame_cost_benefit/ puttit
	make -C estimated_life_expectancy/ puttit
	make -C short_and_mid_range_forecasting_accuracy/ puttit
	make -C masturbation_and_attractiveness/ puttit
	make -C bp_chrono/ puttit
	make -C ob_chrono/ puttit
	make -C so_chrono/ puttit
	make -C trm_chrono/ puttit

clean:
	make -C 99_klong/ clean
	make -C considerations_on_cryonics/ clean
	make -C daygame_cost_benefit/ clean
	make -C estimated_life_expectancy/ clean
	make -C short_and_mid_range_forecasting_accuracy/ clean
	make -C masturbation_and_attractiveness/ clean
	make -C naive_set_theory/ clean
	make -C bp_chrono/ clean
	make -C ob_chrono/ clean
	make -C so_chrono/ clean
	make -C trm_chrono/ clean
