all:
	make -C 99_klong/
	make -C cryonics/
	make -C daygame/
	make -C estimated_life_expectancy/
	make -C range/
	make -C masturbation/
	make -C naive_set_theory/
	make -C bp_chrono/
	make -C ob_chrono/
	make -C so_chrono/
	make -C trm_chrono/

puttit:
	make -C 99_klong/ puttit
	make -C cryonics/ puttit
	make -C daygame/ puttit
	make -C estimated_life_expectancy/ puttit
	make -C range/ puttit
	make -C masturbation / puttit
	make -C bp_chrono/ puttit
	make -C ob_chrono/ puttit
	make -C so_chrono/ puttit
	make -C trm_chrono/ puttit

clean:
	make -C 99_klong/ clean
	make -C cryonics/ clean
	make -C daygame/ clean
	make -C estimated_life_expectancy/ clean
	make -C range/ clean
	make -C masturbation / clean
	make -C naive_set_theory/ clean
	make -C bp_chrono/ clean
	make -C ob_chrono/ clean
	make -C so_chrono/ clean
	make -C trm_chrono/ clean
