all:
	make -C 99_klong/
	make -C estimated_life_expectancy/
	make -C bp_chrono/
	make -C ob_chrono/
	make -C so_chrono/
	make -C trm_chrono/

puttit:
	make -C 99_klong/ puttit
	make -C estimated_life_expectancy/ puttit
	make -C bp_chrono/ puttit
	make -C ob_chrono/ puttit
	make -C so_chrono/ puttit
	make -C trm_chrono/ puttit

clean:
	make -C 99_klong/ clean
	make -C estimated_life_expectancy/ clean
	make -C bp_chrono/ clean
	make -C ob_chrono/ clean
	make -C so_chrono/ clean
	make -C trm_chrono/ clean
